languages_detect = {
    'af': 'afrikaans',
    'sq': 'albanian',
    'am': 'amharic',
    'ar': 'arabic',
    'hy': 'armenian',
    'az': 'azerbaijani',
    'eu': 'basque',
    'be': 'belarusian',
    'bn': 'bengali',
    'bs': 'bosnian',
    'bg': 'bulgarian',
    'ca': 'catalan',
    'ceb': 'cebuano',
    'ny': 'chichewa',
    'zh-cn': 'chinese (simplified)',
    'zh-tw': 'chinese (traditional)',
    'co': 'corsican',
    'hr': 'croatian',
    'cs': 'czech',
    'da': 'danish',
    'nl': 'dutch',
    'en': 'english',
    'eo': 'esperanto',
    'et': 'estonian',
    'tl': 'filipino',
    'fi': 'finnish',
    'fr': 'french',
    'fy': 'frisian',
    'gl': 'galician',
    'ka': 'georgian',
    'de': 'german',
    'el': 'greek',
    'gu': 'gujarati',
    'ht': 'haitian creole',
    'ha': 'hausa',
    'haw': 'hawaiian',
    'iw': 'hebrew',
    'he': 'hebrew',
    'hi': 'hindi',
    'hmn': 'hmong',
    'hu': 'hungarian',
    'is': 'icelandic',
    'ig': 'igbo',
    'id': 'indonesian',
    'ga': 'irish',
    'it': 'italian',
    'ja': 'japanese',
    'jw': 'javanese',
    'kn': 'kannada',
    'kk': 'kazakh',
    'km': 'khmer',
    'ko': 'korean',
    'ku': 'kurdish (kurmanji)',
    'ky': 'kyrgyz',
    'lo': 'lao',
    'la': 'latin',
    'lv': 'latvian',
    'lt': 'lithuanian',
    'lb': 'luxembourgish',
    'mk': 'macedonian',
    'mg': 'malagasy',
    'ms': 'malay',
    'ml': 'malayalam',
    'mt': 'maltese',
    'mi': 'maori',
    'mr': 'marathi',
    'mn': 'mongolian',
    'my': 'myanmar (burmese)',
    'ne': 'nepali',
    'no': 'norwegian',
    'or': 'odia',
    'ps': 'pashto',
    'fa': 'persian',
    'pl': 'polish',
    'pt': 'portuguese',
    'pa': 'punjabi',
    'ro': 'romanian',
    'ru': 'russian',
    'sm': 'samoan',
    'gd': 'scots gaelic',
    'sr': 'serbian',
    'st': 'sesotho',
    'sn': 'shona',
    'sd': 'sindhi',
    'si': 'sinhala',
    'sk': 'slovak',
    'sl': 'slovenian',
    'so': 'somali',
    'es': 'spanish',
    'su': 'sundanese',
    'sw': 'swahili',
    'sv': 'swedish',
    'tg': 'tajik',
    'ta': 'tamil',
    'te': 'telugu',
    'th': 'thai',
    'tr': 'turkish',
    'uk': 'ukrainian',
    'ur': 'urdu',
    'ug': 'uyghur',
    'uz': 'uzbek',
    'vi': 'vietnamese',
    'cy': 'welsh',
    'xh': 'xhosa',
    'yi': 'yiddish',
    'yo': 'yoruba',
    'zu': 'zulu'
}

languages_translate = {
    'afrikaans': 'af',
    'albanian': 'sq',
    'amharic': 'am',
    'arabic': 'ar',
    'armenian': 'hy',
    'azerbaijani': 'az',
    'basque': 'eu',
    'belarusian': 'be',
    'bengali': 'bn',
    'bosnian': 'bs',
    'bulgarian': 'bg',
    'catalan': 'ca',
    'cebuano': 'ceb',
    'chichewa': 'ny',
    'chinese': 'zh-cn',
    'chinese_traditional': 'zh-tw',
    'corsican': 'co',
    'croatian': 'hr',
    'czech': 'cs',
    'danish': 'da',
    'dutch': 'nl',
    'english': 'en',
    'esperanto': 'eo',
    'estonian': 'et',
    'filipino': 'tl',
    'finnish': 'fi',
    'french': 'fr',
    'frisian': 'fy',
    'galician': 'gl',
    'georgian': 'ka',
    'german': 'de',
    'greek': 'el',
    'gujarati': 'gu',
    'haitian': 'ht',
    'hausa': 'ha',
    'hawaiian': 'haw',
    'hebrew': 'iw',
    'hebrew': 'he',
    'hindi': 'hi',
    'hmong': 'hmn',
    'hungarian': 'hu',
    'icelandic': 'is',
    'igbo': 'ig',
    'indonesian': 'id',
    'irish': 'ga',
    'italian': 'it',
    'japanese': 'ja',
    'javanese': 'jw',
    'kannada': 'kn',
    'kazakh': 'kk',
    'khmer': 'km',
    'korean': 'ko',
    'kurdish (kurmanji)': 'ku',
    'kyrgyz': 'ky',
    'lao': 'lo',
    'latin': 'la',
    'latvian': 'lv',
    'lithuanian': 'lt',
    'luxembourgish': 'lb',
    'macedonian': 'mk',
    'malagasy': 'mg',
    'malay': 'ms',
    'malayalam': 'ml',
    'maltese': 'mt',
    'maori': 'mi',
    'marathi': 'mr',
    'mongolian': 'mn',
    'myanmar (burmese)': 'my',
    'nepali': 'ne',
    'norwegian': 'no',
    'odia': 'or',
    'pashto': 'ps',
    'persian': 'fa',
    'polish': 'pl',
    'portuguese': 'pt',
    'punjabi': 'pa',
    'romanian': 'ro',
    'russian': 'ru',
    'samoan': 'sm',
    'scots gaelic': 'gd',
    'serbian': 'sr',
    'sesotho': 'st',
    'shona': 'sn',
    'sindhi': 'sd',
    'sinhala': 'si',
    'slovak': 'sk',
    'slovenian': 'sl',
    'somali': 'so',
    'spanish': 'es',
    'sundanese': 'su',
    'swahili': 'sw',
    'swedish': 'sv',
    'tajik': 'tg',
    'tamil': 'ta',
    'telugu': 'te',
    'thai': 'th',
    'turkish': 'tr',
    'ukrainian': 'uk',
    'urdu': 'ur',
    'uyghur': 'ug',
    'uzbek': 'uz',
    'vietnamese': 'vi',
    'welsh': 'cy',
    'xhosa': 'xh',
    'yiddish': 'yi',
    'yoruba': 'yo',
    'zulu': 'zu'
}

galacticlangtranslate1 = {
    "all": "ʖᓵ↸ᒷ⋮⊣⍑╎⋮ꖌꖎᒲリ𝙹!¡ᑑ∷ᓭℸ ̣ ⚍⍊∴ ̇/||⨅",
    "a": 'ᔑ',
    "b": 'ʖ',
    "c": "ᓵ",
    "d": "↸",
    "e": "ᒷ",
    "f": "⋮",
    "g": "⊣",
    "h": "⍑",
    "i": "╎",
    "j": "⋮",
    "k": "ꖌ",
    "l": "ꖎ",
    "m": "ᒲ",
    "n": "リ",
    "o": "𝙹",
    "p": "!",
    "q": "¡",
    "r": "ᑑ",
    "s": "∷",
    "t": "ᓭ",
    "u": "ℸ",
    "v": "⍊",
    "w": "∴",
    "x": "̇/",
    "y": "||",
    "z": "⨅",
    " ": " "
}

power_active_keys = [
    "aussiefriday:master_of_climbing",
    "origins:launch_into_air",
    "origins:throw_ender_pearl",
    "origins:water_vision",
    "aussiefriday:phantom"
]


hidden_powers = [
    "origins:arthropod",
    "origins:lay_eggs",
    "origins:flame_particles",
    "origins:damage_from_snowballs",
    "origins:damage_from_potions",
    "origins:ender_particles",
    "origins:aquatic",
    "origins:conduit_power_on_land",
    "origins:air_from_potions",
    "origins:translucent"
]

debuff = [
    "origins:fragile",
    "origins:carnivore",
    "origins:fresh_air",
    "origins:vegetarian",
    "origins:nether_spawn",
    "origins:water_vulnerability",
    "origins:light_armor",
    "origins:claustrophobia",
    "origins:more_kinetic_damage",
    "origins:pumpkin_hate",
    "origins:nine_lives",
    "origins:weak_arms",
    "origins:water_breathing",
    "origins:burn_in_daylight",
    "origins:no_shield",
    "origins:no_shield",
    "origins:no_shield",
    "origins:no_shield",
    "origins:no_shield",
    "origins:more_exhaustion"
]

buff = [
    "origins:slow_falling",
    "origins:like_air",
    "origins:tailwind",
    "origins:fire_immunity",
    "origins:burning_wrath",
    "origins:hotblooded",
    "origins:winged",
    "origins:aerial_combatant",
    "origins:extra_reach",
    "origins:fall_immunity",
    "origins:sprint_jump",
    "origins:velvet_paws",
    "origins:scare_creepers",
    "origins:cat_vision",
    "origins:water_vision",
    "origins:aqua_affinity",
    "origins:swim_speed",
    "origins:like_water",
    "origins:natural_armor",
    "origins:strong_arms_break_speed"
]

icon = [
    "minecraft:cobweb",
    "minecraft:feather",
    "minecraft:blaze_powder",
    "minecraft:elytra",
    "minecraft:ender_pearl",
    "minecraft:orange_wool",
    "minecraft:cod",
    "minecraft:phantom_membrane",
    "minecraft:shulk"
]

name = [
    "Arachnid",
    "Avian",
    "Blazeborn",
    "Elytrian",
    "Enderian",
    "Feline",
    "Merling",
    "Phantom",
    "Shulk"
]

description = [
    "Their climbing abilities and the ability to trap their foes in spiderweb make the Arachnid perfect hunters.",
    "The Avian race has lost their ability to fly a long time ago. Now these peaceful creatures can be seen gliding from one place to another.",
    "Late descendants of the Blaze, the Blazeborn are naturally immune to the perils of the Nether."
    "Often flying around in the winds, Elytrians are uncomfortable when they don't have enough space above their head.",
    "Born as sons and daughters of the Ender Dragon, Enderians are capable of teleporting but are vulnerable to water.",
    "With their cat-like appearance, the Feline scare creepers away. With the dexterity of cats, they always land safely on their feet.",
    "These natural inhabitants of the ocean are not used to being out of the water for too long.",
    "As half-human and half-phantom offspring, these creatures can switch between a Phantom and a normal form.",
    "Related to Shulkers, the bodies of the Shulk are outfitted with a protective shell-like skin."
]
